apiVersion: apps/v1
kind: Deployment
metadata:
 name: note-app-deployment
 labels:
   web: note
 
spec:
 replicas: 2
 selector:
  matchLabels:
    web: note
 template:
  metadata:
    labels:
      web: note
  spec:
    containers:
     - name: note-app
       image: bakhtawar375/PRO2:latest
       ports:
         - containerPort: 8000
       imagePullPolicy: always
 
 
