apiVersion: v1
kind: Service
metadata:
 labels:
   web: note

spec: 
  type: NodePort
  selector: 
   matchLabels:
     web: note
  ports:
    - targetPort: 8000 # container port
      port: 80         # Node internal port
      NodePort: 30003  # port on which service expose to outside world 
    
