apiVersion: v1
kind: Service
metadata:
  name: note-service
  labels:
    web: note
spec:
  type: NodePort
  selector:
     web: note
  ports:
    - targetPort: 8000  # Container port
      port: 8000          # Node internal port
      nodePort: 30005   # Port on which the service exposes to the outside world
